//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aptekaaaa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderss
    {
        public Orderss()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int OrderID { get; set; }
        public System.DateTime OrderDates { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public int CustomerID { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
