//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aptekaaaa
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsInWarehouses
    {
        public int id { get; set; }
        public int idproduct { get; set; }
        public int idwarehouses { get; set; }
        public int Count { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
